/*
Copyright 2018 caicloud authors. All rights reserved.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/caicloud/clientset/kubernetes/typed/cargo/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeResourceV1 struct {
	*testing.Fake
}

func (c *FakeResourceV1) Cargos(namespace string) v1.CargoInterface {
	return &FakeCargos{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeResourceV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
