/*
Copyright 2018 caicloud authors. All rights reserved.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/caicloud/clientset/kubernetes/typed/tenant/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeTenantV1alpha1 struct {
	*testing.Fake
}

func (c *FakeTenantV1alpha1) ClusterQuotas() v1alpha1.ClusterQuotaInterface {
	return &FakeClusterQuotas{c}
}

func (c *FakeTenantV1alpha1) Partitions() v1alpha1.PartitionInterface {
	return &FakePartitions{c}
}

func (c *FakeTenantV1alpha1) Tenants() v1alpha1.TenantInterface {
	return &FakeTenants{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeTenantV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
