/*
Copyright 2018 caicloud authors. All rights reserved.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/caicloud/clientset/pkg/apis/tenant/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTenants implements TenantInterface
type FakeTenants struct {
	Fake *FakeTenantV1alpha1
}

var tenantsResource = schema.GroupVersionResource{Group: "tenant.caicloud.io", Version: "v1alpha1", Resource: "tenants"}

var tenantsKind = schema.GroupVersionKind{Group: "tenant.caicloud.io", Version: "v1alpha1", Kind: "Tenant"}

// Get takes name of the tenant, and returns the corresponding tenant object, and an error if there is any.
func (c *FakeTenants) Get(name string, options v1.GetOptions) (result *v1alpha1.Tenant, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(tenantsResource, name), &v1alpha1.Tenant{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Tenant), err
}

// List takes label and field selectors, and returns the list of Tenants that match those selectors.
func (c *FakeTenants) List(opts v1.ListOptions) (result *v1alpha1.TenantList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(tenantsResource, tenantsKind, opts), &v1alpha1.TenantList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TenantList{}
	for _, item := range obj.(*v1alpha1.TenantList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested tenants.
func (c *FakeTenants) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(tenantsResource, opts))
}

// Create takes the representation of a tenant and creates it.  Returns the server's representation of the tenant, and an error, if there is any.
func (c *FakeTenants) Create(tenant *v1alpha1.Tenant) (result *v1alpha1.Tenant, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(tenantsResource, tenant), &v1alpha1.Tenant{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Tenant), err
}

// Update takes the representation of a tenant and updates it. Returns the server's representation of the tenant, and an error, if there is any.
func (c *FakeTenants) Update(tenant *v1alpha1.Tenant) (result *v1alpha1.Tenant, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(tenantsResource, tenant), &v1alpha1.Tenant{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Tenant), err
}

// Delete takes name of the tenant and deletes it. Returns an error if one occurs.
func (c *FakeTenants) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(tenantsResource, name), &v1alpha1.Tenant{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTenants) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(tenantsResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.TenantList{})
	return err
}

// Patch applies the patch and returns the patched tenant.
func (c *FakeTenants) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Tenant, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(tenantsResource, name, data, subresources...), &v1alpha1.Tenant{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Tenant), err
}
